[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "v0.8.0"

[[constraint]]
  name = "github.com/oklog/oklog"
  version = "v0.3.0"

[[constraint]]
  name = "go.uber.org/zap"
  version = "v1.7.1"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "v1.1.0"